name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: sail

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          for path in runtimes/*; do
            TAG=$(echo ${p##*/})
            docker build -t "$GITHUB_REPOSITORY" -f "$path/Dockerfile" "$path" --build-arg WWWGROUP=1000
          done

  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: build images
        run: |
          for path in runtimes/*; do
            docker build -t "$GITHUB_REPOSITORY" -f "$path/Dockerfile" "$path/" --build-arg WWWGROUP=1000
          done

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}

          echo $IMAGE_ID



